### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by sonvirgo** [sgan81/apfs-fuse#13]
``` 
fdisk -l /dev/sda
Disk /dev/sda: 111.8 GiB, 120034123776 bytes, 234441648 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: CFD0A84A-432E-4B84-A831-0BDCE634E061

Device         Start       End   Sectors  Size Type
/dev/sda1       2048     34815     32768   16M Microsoft reserved
/dev/sda2      67584    579583    512000  250M EFI System
/dev/sda3   10772480 102928383  92155904   44G unknown
/dev/sda4  102928384 234440703 131512320 62.7G Microsoft basic data

Reading symbols from apfs-fuse...done.
(gdb) set args -d1 /dev/sda3 /mnt/osx
(gdb) run
Starting program: /root/Downloads/Compressed/apfs-fuse-master/build/bin/apfs-fuse -d1 /dev/sda3 /mnt/osx
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Device /dev/sda3 opened. Size is 47183822848 bytes.

Program received signal SIGSEGV, Segmentation fault.
0x000055555556be2e in BTreeNode::level (this=0x0)
    at /root/Downloads/Compressed/apfs-fuse-master/ApfsLib/BTree.h:79
79		uint16_t level() const { return m_bt->level; }
(gdb) backtrace
#0  0x000055555556be2e in BTreeNode::level (this=0x0)
    at /root/Downloads/Compressed/apfs-fuse-master/ApfsLib/BTree.h:79
#1  0x000055555556a513 in BTree::Lookup (this=0x55555579d948, result=..., 
    key=0x7fffffffde10, key_size=16, 
    func=0x555555560b04 <CompareNodeMapKey(void const*, size_t, void const*, size_t, void*)>, context=0x55555579c948, exact=false)
    at /root/Downloads/Compressed/apfs-fuse-master/ApfsLib/BTree.cpp:211
#2  0x0000555555560e59 in ApfsNodeMapperBTree::GetBlockID (
    this=0x55555579c948, info=..., nodeid=1027, version=25187)
    at /root/Downloads/Compressed/apfs-fuse-master/ApfsLib/ApfsNodeMapperBTree.cpp:89
#3  0x000055555555ce85 in ApfsContainer::GetVolume (this=0x55555579c280, 
    index=0)
    at /root/Downloads/Compressed/apfs-fuse-master/ApfsLib/ApfsContainer.cpp:98
#4  0x000055555555ad06 in main (argc=4, argv=0x7fffffffe028)
    at /root/Downloads/Compressed/apfs-fuse-master/apfsfuse/ApfsFuse.cpp:594
(gdb) 
```

**Comment by sgan81** [comment]
See issue #10.
